

### /
GET http://{{location}}/


### /user/register

POST http://{{location}}/user/register
Content-Type: application/json

{
  "nickname": "测试注册@sprintbootTest",
  "password": "123456",
  "email": "test@abc.com"
}

### /user/login

POST http://{{location}}/user/login
Content-Type: application/json

{
    "uid": "100002",
    "password": "12345678",
    "deviceCode": "3fffb736-ebc1-429e-8a54-f66670fd7064",
    "deviceName": "HttpUnitTest",
    "platformCode": "2"
}

> {% client.global.set("auth_token", response.body.data.token); %}

### user/state
POST http://{{location}}/user/state
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### /me
GET http://{{location}}/me
Authorization: Bearer {{auth_token}}

### /dailyset/info
POST http://{{location}}/dailyset/info
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### /dailyset/update
POST http://{{location}}/dailyset/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "uid": "#school.zjut.global",
  "type": 4,
  "sourceVersion": 0,
  "matteVersion": 0,
  "metaVersion": 0
}

### /dailyset/update <course>
POST http://{{location}}/dailyset/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "uid": "#school.zjut.course.201806061201",
  "type": 2,
  "sourceVersion": 0,
  "matteVersion": 0,
  "metaVersion": 0
}

### /dailyset/update <unic>
POST http://{{location}}/dailyset/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "uid": "#school.zjut.unic",
  "type": 4,
  "sourceVersion": 0,
  "matteVersion": 0,
  "metaVersion": 0
}

### /message/post/system
POST http://{{location}}/message/post/system
Content-Type: application/json

{
  "secret": "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1MjE2ODE4NiwiaWF0IjoxNjUyMTY4MTg2fQ.ATg-DVcatCozc4UOfasef7BbgKqYkETjUE4vx3bu2DM",
  "targets": ["100002"],
  "intent": {
    "topic": "system",
    "referer": "system",
    "code": 0,
    "content": "HttpUnitTest发送了一条测试消息"
  }
}