version: '3.1'

services:
  dailyset-cloud-mysql:
    container_name: dailyset_cloud_mysql
    image: dailyset_cloud/mysql
    restart: always
    build:
      context: ./mysql/
      dockerfile: ./mysql.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: SNWeofpheYpKtlNAzfhoqACQiFYkqJRl
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
  dailyset-cloud-server:
    container_name: dailyset_cloud_server
    image: dailyset_cloud/server
    restart: always
    build: 
        context: ./cloud/
        dockerfile: ./cloud.Dockerfile
    depends_on:
      - dailyset-cloud-mysql
    ports:
      - "8086:8086"
      - "8087:8087"
  dailyset-cloud-unic:
    container_name: dailyset_cloud_unic
    image: dailyset_cloud/unic
    restart: always
    build:
      context: ./unic/
      dockerfile: ./unic.Dockerfile
    depends_on:
      - dailyset-cloud-mysql
    ports:
      - "8088:8088"
      - "8089:8089"